### PR TITLE
driver/qemudriver: add drive interface and kernel boot parameters

### PR DESCRIPTION
**Pull request by EmilKronborg**
**Description**
Make the `q35` machine behave similar to `pc` if a kernel is started directly. Furthermore, the default drive interface has been added. This commit is an addition to `086ba3b3fe1e04bcc8cba0e6dfe558b7747d372d`.

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [x] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Review by jluebbe — CHANGES_REQUESTED** [review]
I would expect that you'd need `if=virtio` to get `root=/dev/vda` to work.

**Comment by EmilKronborg** [comment]
> I would expect that you'd need `if=virtio` to get `root=/dev/vda` to work.

You're right. Let's keep the interface out for now. I rewrote the commit message to reflect this change.

**Comment by jluebbe** [comment]
Does it work this way? You said that q35 defaults to IDE in https://github.com/labgrid-project/labgrid/pull/961#discussion_r938193620.

My preferred approach would be `if=virtio`, as that avoids the need for legacy IDE drivers.

**Comment by EmilKronborg** [comment]
> 

In my case, I am using a bios image (`.qcow2`) and a raw image (`.wic`) to mount my filesystem. This setup fails with anything but the standard interface, i.e., `if=ide`. If there was a way to override the interface, I could add `virtio` to make q35 and pc more similar, but as far as I can tell you're not able to override it?

**Comment by jluebbe** [comment]
Ah. You could not set the `disk` property, as then no `-drive` property would be generated. Then you could pass that via the `extra_args` property.

**Comment by EmilKronborg** [comment]
OK. That solution is not as elegant as using the `disk` property, but I can live with that. I will rather get going with tests for our project. I added `if=virtio` and rewrote the commit message.

**Review by jluebbe — APPROVED** [review]

**Comment by jluebbe** [comment]
Thanks a lot for your contribution!

**Pull request merged**
