### PR TITLE
pyproject.toml: specify build-system requirements

### PR DESCRIPTION
**Pull request by S4mw1s3**
Using pyproject.toml to specify build system requirements is now the
preferred way. From the setuptools documentation[1]:

"This used to be accomplished with the setup_requires keyword but is now
considered deprecated in favor of the PEP 517 style described above."

I didn't remove the 'setup_requires' from setup.py because some users
who are using older versions of setuptools might still rely on it if
their version of setuptools has no support for pyproject.toml.

Without this pyproject.toml, the following command fails on a local
network without internet access:

[edit: correct command as explained below in the comments]
  `pip install --index-url <local index> -e .`

because setuptools does not take the index into account when fetching
the 'setup_requires' dependencies defined in setup.py.

However, with the correct pyproject.toml available, the build system
requirements are fetched first, using the correct index, and then later
at the point where setuptools tries to install the 'setup_requires'
dependencies, they are already installed so no need to fetch anything
anymore.

[1]: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [ ] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Review by Emantor — APPROVED** [review]

**Comment by Bastian-Krause** [comment]
> pip install --index -e .

Where is the `--index` option documented?

**Comment by S4mw1s3** [comment]
> Where is the --index option documented?

Eh well... I always thought it was a valid argument to pip install but I just learned that python by default allows argument abbreviations if the abbreviation is unambiguous: https://docs.python.org/3.10/library/argparse.html#argument-abbreviations-prefix-matching so in fact what I meant here is the '--index-url' option.

Also, bad copy/paste from my commit message because in there in fact I wrote:

`pip install --index <local index> -e .` but looks like github removed the `<local index>` part.

If you want I can update the commit message so it states --index-url.

**Comment by Bastian-Krause** [comment]
@S4mw1s3 Okay, yes, please update the commit message accordingly. Thanks!

**Comment by S4mw1s3** [comment]
> @S4mw1s3 Okay, yes, please update the commit message accordingly. Thanks!

Done. The commit message now clearly states
`pip install --index-url <local index> -e .`

**Comment by Bastian-Krause** [comment]
Thanks!

**Review by Emantor — APPROVED** [review]

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
