### PR TITLE
Add Flash Scripting Driver

### PR DESCRIPTION
**Pull request by JoshuaWatt**
Some SoC vendors have complex and SoC specific protocols and programs
that are required to flash software on their devices. Instead of trying
to implement drivers for all of these one-off implementations, implement
the surgical chain-saw approach and add support for sending a "flashing
script" to be run on the exporter which will flash the device.

A typical use case might be creating a self extracting flashing script
with e.g. makeself that contains the image files and all flashing
utilities.

Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>

**Description**

**Checklist**
- [x] Documentation for the feature
- [x] Tests for the feature 

- [x] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [x] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Comment by jluebbe** [comment]
If fixed a typo and made some formatting changes (semantic newlines).

**Review by jluebbe — APPROVED** [review]
While I'd prefer having Resources and Drivers with proper abstractions, I can see the need of having this escape hatch mechanism.

**Comment by jluebbe** [comment]
@Emantor Are you OK with merging this?

**Comment by Emantor** [comment]
> While I'd prefer having Resources and Drivers with proper abstractions, I can see the need of having this escape hatch mechanism.

Definitely, real resources and drivers offer several advantages.

> @Emantor Are you OK with merging this?

Fine by me.

**Pull request merged**
