### PR TITLE
dockerfiles: support for docker buildx

### PR DESCRIPTION
**Pull request by rpoisel**
**Description**

This allows for building docker images for different platforms such as linux/arm64 .

I am using this feature because in my case the labgrid coordinator will be executed on a Raspberry Pi 4 in a `docker compose` environment.

**Checklist**
- [x] Documentation for the feature
- [x] PR has been tested manually

### CODE REVIEW

**Comment by obbardc** [comment]
does this upload the new container images to dockerhub in the CI build as well ?

**Comment by Emantor** [comment]
> does this upload the new container images to dockerhub in the CI build as well ?

**Comment by rpoisel** [comment]
> > does this upload the new container images to dockerhub in the CI build as well ?
> AFAICS the github actions haven't been adjusted.

Yes, that's right. In a first step, I made sure that the calling interface of the script stays compatible with the original.

I suggest adding uploading the new container images to dockerhub in a separate PR after this one is merged. What do you think?

**Comment by Emantor** [comment]
At least my local `podman` also supports `buildx`, so I don't see why we are restricting this to docker:
```
$ podman buildx                                                                                                                                                                             
Build images

Description:
  Build images

Usage:
  podman buildx [command]

Aliases:
  buildx, builder

Available Commands:
  build       Build an image using instructions from Containerfiles
  prune       Remove unused images
  version     Print build version

Error: missing command 'podman buildx COMMAND'
```

**Comment by rpoisel** [comment]
> At least my local `podman` also supports `buildx`, so I don't see why we are restricting this to docker.

Yes, agreed. Didn't know that, but I can reproduce that locally.

I'll update the script to support `podman buildx` too.

**Comment by jluebbe** [comment]
The DCO sign-off is missing. Please see https://github.com/labgrid-project/labgrid/pull/1091/checks?check_run_id=11605072436 and https://labgrid.readthedocs.io/en/latest/development.html#developer-s-certificate-of-origin.

**Comment by jluebbe** [comment]
As the second commit only changes lines modified in the first already, I'd suggest squashing them into one commit.

**Comment by rpoisel** [comment]
I'll update this PR to incorporate your suggestions. Thanks for you hints!

Unfortunately, for uploading the resulting docker images supporting multiple platforms, the `dockerfiles/build.sh` script would have to be changed again - most likely with a different calling interface. Therefore, I suggest to postpone this to another PR. Hopefully, I can file this PR in the coming days/weeks.

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
