### PR TITLE
Fix stat command for MacOS

### PR DESCRIPTION
**Pull request by jpuderer**
**Description**

The managedfile class uses the 'stat' command locally, which has a different syntax on MacOS.  Everything otherwise seems to work quite well on MacOS.  Just added different arguments when using MacOS.

**Checklist**
- [x] PR has been tested

### CODE REVIEW

**Comment by jluebbe** [comment]
Does this actually produce the same output for the same file on a NFS mount between client and exporter?

**Comment by jpuderer** [comment]
Yes indeed.

On the server (Ubuntu):
```
jpuderer@crius:~$ cd /nfs
jpuderer@crius:/nfs$ df .
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p2 490617784 301803256 163819048  65% /
jpuderer@crius:/nfs$ ls
foobar
jpuderer@crius:/nfs$ stat --format inode=%i,size=%s,modified=%Y foobar 
inode=28049410,size=3912,modified=1686142787
```

On the client (MacOS):
```
Rocinante:nfs jpuderer$ df .
Filesystem          512-blocks      Used Available Capacity iused    ifree %iused  Mounted on
192.168.50.234:/nfs  981235568 603606496 327638112    65% 5234000 25993904   17%   /Users/jpuderer/nfs
Rocinante:nfs jpuderer$ ls
foobar
Rocinante:nfs jpuderer$ stat -f inode=%i,size=%z,modified=%m foobar
inode=28049410,size=3912,modified=1686142787
```

**Review by jluebbe — APPROVED** [review]

**Comment by jluebbe** [comment]
@Emantor @Bastian-Krause We should wait for test feedback before merging this.

**Comment by jpuderer** [comment]
Tested.  No issue.  Thanks for the fixup and review!

**Review by Emantor — APPROVED** [review]

**Pull request merged**
