### PR TITLE
Add simplerest model for NetworkPowerPort

### PR DESCRIPTION
**Pull request by kjeldflarup**
Adds a generic powercontroller for NetworkPowerPort  using http get rest calls.
It uses a "Tweak" in NetworkPowerPort declaration where anything can be written in the "host" field.

### CODE REVIEW

**Comment by jluebbe** [comment]
If I read it correctly, this only works for power controllers which use 'on'/'off' while set and '0'/'1' for get? The "networkpowerurl" model name is probably too generic for this behavior. Is this for some specific hardware? Or do you have several different models which all use this REST API?

**Comment by kjeldflarup** [comment]
The primary target is Raspberry Pi, which can implement power relay in many ways. Making a rest server using flask is a simple task.
A typical setup is to connect a solid state relay directly to a GPIO pin.

Regarding on/off, You are right, that ought to be 0/1, which my rest server also supports.

**Comment by jluebbe** [comment]
Ah, OK. Maybe rename it to simplerest. networkpowerurl is too generic for this.
I'll then squash and merge it.

**Comment by kjeldflarup** [comment]
I have renamed to simplerest, but it just occurred to me that the --hostname in https://github.com/labgrid-project/labgrid/pull/218 might come in handy.  
I will thus test with storing the URL in "index" instead. That might also be more appropriate.  
But is there a way to use --hostname, or should I just write:  
`host: !template $LG_IP`

**Comment by kjeldflarup** [comment]
Another caveat is that index is parsed as an integer. So I will have to stick with tweaking "host"
That has already been pushed to the PR

**Pull request merged**
