### PR TITLE
Search environment for crossbar

### PR DESCRIPTION
**Pull request by kjeldflarup**
Uses the environment variable LG_CROSSBAR and LG_CROSSBAR_REALM as defaults for crossbar URL, if they are set.

### CODE REVIEW

**Comment by jluebbe** [comment]
I've updated your PR with some documentation and reworded the commit message a bit.
Also, the Signed-off-by line is missing, see: https://labgrid.readthedocs.io/en/latest/development.html#developer-s-certificate-of-origin

**Comment by kjeldflarup** [comment]
I'm not really sure how to fix the missing sign-off, the time --amend trick seems to be passed as I merged upstream before pushing to githup.

**Comment by jluebbe** [comment]
If you are OK with it, I can also add "Signed-off-by: Kjeld Flarup <kfa@deif.com>" myself by rebasing it. Otherwise you can add it yourself by updating, editing the message using "git rebase -i" and force-pushing.

**Comment by kjeldflarup** [comment]
It seems that I succeded!

**Pull request merged**
