### PR TITLE
dockerfiles: change debian to ubuntu as base image

### PR DESCRIPTION
**Pull request by ekronborg**
* Using `scp -s` with the SSHDriver requires OpenSSH >= 8.6, but Debian Bullseye only provides OpenSSH 8.4, while Ubuntu 22.04 provides OpenSSH 8.9. Therefore, changing the base image from Debian to Ubuntu allows using the SFTP protocol in containers. For more information, see https://github.com/labgrid-project/labgrid/pull/1003.
* This will increase the image sizes slightly. For example, the labgrid client image is 869 MB with Debian as base image, while it is 952 MB with Ubuntu as base image.

Signed-off-by: Emil Kronborg Andersen <emil.kronborg@protonmail.com>

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [x] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Review by krevsbech — DISMISSED** [review]

**Review by Bastian-Krause — CHANGES_REQUESTED** [review]
I have no opinion on the base image change, but there are a few things to consider:
- https://github.com/labgrid-project/labgrid/commit/30a0e38ca5f38a5e048b47a6d09371e411655112 can probably be dropped now
- what about the base image version in `dockerfiles/staging/dut/Dockerfile`?

**Comment by ekronborg** [comment]
>     * [30a0e38](https://github.com/labgrid-project/labgrid/commit/30a0e38ca5f38a5e048b47a6d09371e411655112) can probably be dropped now
You are right. Joshua made this commit to build version 4.3.3. In Ubuntu 22.04, ser2net is version 4.3.4.

>     * what about the base image version in `dockerfiles/staging/dut/Dockerfile`?
I changed that as well.

**Review by Bastian-Krause — COMMENTED** [review]
Please add a short explanation why you revert the commit, so the git history contains all necessary information and we do not need to dig into the PR comments later.

Apart from that, this looks okay to me. I'd still like a comment from @Emantor or @jluebbe.

**Comment by ekronborg** [comment]
> Please add a short explanation why you revert the commit, so the git history contains all necessary information and we do not need to dig into the PR comments later.

I changed the commit message to include an explanation of the revert.

**Review by Bastian-Krause — APPROVED** [review]
Thanks. Note that I don't have an opinion on the debian:buster-slim -> ubuntu:22.04 move.

**Comment by obbardc** [comment]
Why the move from debian -> ubuntu ?

**Comment by Emantor** [comment]
@obbardc The reasoning concerning SSH support. However I am not sure that we want to switch over the default docker images. IMO the next debian release shouldn't be too far away and it's always possible to build your own containers to get the necessary software.

**Comment by Bastian-Krause** [comment]
As a first step, I've bumped the docker base image to Debian bullseye: #1129. I guess Debian bookworm will become stable around July.

**Comment by ekronborg** [comment]
> As a first step, I've bumped the docker base image to Debian bullseye: #1129. I guess Debian bookworm will become stable around July.

Bumping the image is fine, but please note that Bullseye still uses `OpenSSH 8.4`. Hopefully, it will be bumped to 8.6+ in the Bookworm release.

**Comment by Bastian-Krause** [comment]
> > As a first step, I've bumped the docker base image to Debian bullseye: #1129. I guess Debian bookworm will become stable around July.
> 
> Bumping the image is fine, but please note that Bullseye still uses `OpenSSH 8.4`. Hopefully, it will be bumped to 8.6+ in the Bookworm release.

[Bookworm contains OpenSSH 9.2](https://packages.debian.org/bookworm/openssh-client).

**Comment by jluebbe** [comment]
Bookworm will likely be released in less than a month, so we shouldn't switch all containers to Ubuntu just for that. If you need a newer OpenSSH, you can just build the container locally from bookworm even before the release.

**Pull request closed without merging**
