### PR TITLE
 config: return passed in tool by default 

### PR DESCRIPTION
**Pull request by Emantor**
**Description**
The tools in the tools key can either be a single string with the binary
name or a complete path to a binary. This works for every tool expect
for qemu since drivers can provide a fallback to the default tool.
However qemu currently requires the user to supply the full binary path,
which is unintuitive.

Instead return the originally requested tool-name instead if no
specialized path is found. And return the simple unexpanded path if a
local tool with the same name can't be found.

**Checklist**
- [x] PR has been tested

### CODE REVIEW

**Comment by Emantor** [comment]
I'll rework this according to local feedback.

**Comment by jluebbe** [comment]
This would fail when the tool has a different path on the exporter.

**Comment by jluebbe** [comment]
Should we also drop all the instances of `or 'tool'` in the drivers?

**Comment by Emantor** [comment]
> Should we also drop all the instances of `or 'tool'` in the drivers?

Yeah, we should do that. I'll push another commit.

**Review by jluebbe — CHANGES_REQUESTED** [review]
This looks good, we just need a test for the tool handling.

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
