### PR TITLE
remote/client: add name argument for power

### PR DESCRIPTION
**Pull request by strumtrar**
**Description**

Add an optional name argument for the power command to support
places with multiple power drivers.

One or multiple names can be supplied.

Tested locally on a place with two NetworkPowerPorts and with labgrid-pytest.

Signed-off-by: Steffen Trumtrar <s.trumtrar@pengutronix.de>

### CODE REVIEW

**Comment by jluebbe** [comment]
As discussed internally, this needs to keep the current default and handle finding all power resources as well.

**Comment by avoine** [comment]
I was working on the Sentry agent (https://github.com/labgrid-project/labgrid/pull/595) and realized I need this too. We are doing power supply redundancy tests so we need to power off only one of the port but also all of them by default. Ping me if you want me to give it a shot for a solution.

**Comment by avoine** [comment]
A solution could be to use an "aggregating driver" and changing the method by adding :

  ```
    def power(self):
    [...]
      try:
            drv = target.get_driver(PowerProtocol)
        except NoDriverFoundError:
        for name in names:
                try:
                    for resource in target.resources:
       [...]
```

like for the bootstrap method.

Also, maybe this could be generalized for example for flashing multiple banks with the FlashromDriver, flipping multiple GPIO, etc.

**Comment by Emantor** [comment]
I already have a WIP branch and will probably post it next week.

**Comment by Emantor** [comment]
I'll reopen with my changes.

**Pull request closed without merging**
