### PR TITLE
tests: fix warnings and atexit exceptions

### PR DESCRIPTION
**Pull request by Bastian-Krause**
**Description**
When running the test suite, various warnings and exceptions happen. Some occur because cleanup actions are called explicitly during tests leading to errors once the atexit registered cleanup methods run. Unregister the atexit cleanup methods for these tests explicitly. Another warning happens because not all of pytest's TerminalWriter features that we use are mocked. Extend `MockTW` accordingly.

**Checklist**
- [x] PR has been tested

Fixes #730
Fixes #687

### CODE REVIEW

**Review by Emantor — DISMISSED** [review]

**Review by rohieb — DISMISSED** [review]
Hmm, I did not see such warnings for MockTW when I tested #730, but the StepReporter might have changed in the meantime.

**Comment by Bastian-Krause** [comment]
> Hmm, I did not see such warnings for MockTW when I tested #730, but the StepReporter might have changed in the meantime.

The warning is there since your PR, see the [corresponding GitHub actions run](https://github.com/labgrid-project/labgrid/runs/1969842981?check_suite_focus=true#step:9:63).

**Comment by rohieb** [comment]
> > Hmm, I did not see such warnings for MockTW when I tested #730, but the StepReporter might have changed in the meantime.
> 
> @rohieb The warning is there since your PR, see the [corresponding GitHub actions run](https://github.com/labgrid-project/labgrid/runs/1969842981?check_suite_focus=true#step:9:63).

Strange, I didn't see that on my machine when developing the test (maybe it was before I rebased onto then-current master). But it doesn't matter, thank you for fixing it.

**Comment by jluebbe** [comment]
As the warning tells the user "call the cleanup() method on targets yourself to handle exceptions explictly", taking that approach shouldn't lead to further problems. The cleanup functions either need to unregister the atexit handler or be safe to call multiple times.

**Comment by Bastian-Krause** [comment]
Dropped commit 
> tests/externalconsoledriver: unregister cleanup for explicit close call

in favor of #765.

**Review by Emantor — APPROVED** [review]

**Pull request merged**
