### PR TITLE
driver/power: add support for REST based relays controlling power

### PR DESCRIPTION
**Pull request by esben**
**Description**

Add a new driver to support relay based power control where relay is controlled with a REST API with a simple GET/PUT request to the same URL.

This is different from simplerest driver, as it relies on REST interface using
GET to query status, and PUT to change status, where as simplerest driver uses
GET for both purposes.

These two models are therefore inherently incompatible, and supplements each
other.

**Checklist**
- [x] Documentation for the feature
- [x] Tests for the feature 
- [x] CHANGES.rst has been updated
- [x] PR has been tested

### CODE REVIEW

**Comment by Emantor** [comment]
We already have the `simplerest` model for this which coincidentally implements almost the same functions.

**Comment by jluebbe** [comment]
An alternative might be to add this to the existing simplerest driver via a new attribute on the resource... But as almost every line would be different, I'm not sure that would be better.

We need some documentation on when to choose either, though. Otherwise it would be too confusing.

**Comment by esben** [comment]
@jluebbe @Emantor Do you have somewhere in mind where this kind of documentation should be placed?  I didn't find any place where the existing `NetworkPowerDriver` models where documented, other than in the source files themselves.
Would it be sufficient if I try to cleanup the documentation in the top of labgrid/driver/power/rest.py ?

**Comment by jluebbe** [comment]
I've added some documentation on the available backends to the NetworkPowerDriver section.

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
