### PR TITLE
client: Add named resource arg to SSH subparser

### PR DESCRIPTION
**Pull request by tompreston**
Sometimes a remote place might have multiple NetworkService resources,
for example a single device running multiple operating systems.  In this
case, we must specify which NetworkService resource to use for the local
SSHDriver instance.

Signed-off-by: Thomas Preston <thomas.preston@codethink.co.uk>

Testing:
```
(labgrid-venv) $ labgrid-client ssh --help
usage: labgrid-client ssh [-h] [name]

positional arguments:
  name        optional resource name

optional arguments:
  -h, --help  show this help message and exit

(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh guest-os-network
guest-os#

(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh host-os-network
host-os# 
```

**Checklist**
- [x] Documentation for the feature (in the subparser --help docs, I don't think this needs a man page)
- N/A Tests for the feature (I don't think there are labgrid-client tests, and also the SSHDriver binding is already tested)

- N/A The arguments and description in doc/configuration.rst have been updated (not relevant)

- N/A Add a section on how to use the feature to doc/usage.rst (not relevant)

- N/A Add a section on how to use the feature to doc/development.rst (not relevant)

- [x] CHANGES.rst has been updated

- [x] PR has been tested

- N/A Man pages have been regenerated (nope, it doesn't touch the man pages)

### CODE REVIEW

**Review by Emantor — DISMISSED** [review]

**Comment by Bastian-Krause** [comment]
Solves #364 for the ssh subcommand.

**Review by jluebbe — CHANGES_REQUESTED** [review]
Using a positional argument breaks calling a remote binary if no name is needed (as the binary name would be interpreted as the resource name).

**Comment by tompreston** [comment]
I made the `--name` argument optional:
```
(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh -n network1
network1#

(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh -n network2
network2#
```

**Comment by tompreston** [comment]
@

> Using a positional argument breaks calling a remote binary if no name is needed (as the binary name would be interpreted as the resource name).

@jluebbe does this solve your issue? https://github.com/labgrid-project/labgrid/pull/771#issuecomment-821059484

**Review by Emantor — APPROVED** [review]

**Comment by Bastian-Krause** [comment]
What's the overall plan for named resources in labgrid-client? Should all relevant sub-commands accept `--name` in the long run? I'd like to have a consistent way to specify the name of a resource. We could declare passing the name as positional argument legacy(?)

**Comment by jluebbe** [comment]
> What's the overall plan for named resources in labgrid-client? Should all relevant sub-commands accept `--name` in the long run? I'd like to have a consistent way to specify the name of a resource. We could declare passing the name as positional argument legacy(?)

The PR adds this only for `ssh`, but the name handing is generic. So we could add the argument to other subcommands as well.

I've rebased the PR to fix the conflict in `CHANGES.rst`.

**Review by jluebbe — APPROVED** [review]

**Comment by Emantor** [comment]
Thanks for the PR, sorry it took so long.

**Pull request merged**
