### PR TITLE
Add support for usbrelay power control

### PR DESCRIPTION
**Pull request by niecore**
Add resource `USBRelay`
Add driver `USBRelayPowerDriver`

Link to infopage: https://github.com/darrylb123/usbrelay

**Checklist**
- [x] Documentation for the feature
- [ ] Tests for the feature 
- [x] The arguments and description in doc/configuration.rst have been updated
Provide a short summary for the CHANGES.rst file
- [x] CHANGES.rst has been updated
- [x] PR has been tested

### CODE REVIEW

**Comment by niecore** [comment]
In order to make the builds pass I have to:

1. Remove the f-string
2. Check the sphinx syntax

PR will be updated.

**Comment by Emantor** [comment]
We are not really interested in supporting more power driver within labgrid, since the testing infrastructure direction is to use [pdudaemon](https://github.com/pdudaemon/pdudaemon) instead. However this still requires work on [pdudaemon#78](https://github.com/pdudaemon/pdudaemon/pull/78), to have a compatible pdudaemon for labgrid.

**Comment by niecore** [comment]
> We are not really interested in supporting more power driver within labgrid, since the testing infrastructure direction is to use [pdudaemon](https://github.com/pdudaemon/pdudaemon) instead. However this still requires work on [pdudaemon#78](https://github.com/pdudaemon/pdudaemon/pull/78), to have a compatible pdudaemon for labgrid.

Okay, working with PDU`s is probably a good idea. Anyhow the drivers/resources will not interfere, isn't it?
With the usbrelay hw you could setup a very cheap solution for initial testing. (That's what I did now in order to test labgrid for our use case)

**Comment by niecore** [comment]
@Emantor What is your final statement? If you will not integrate the change I would like to close the PR. Otherwise I would work on the merge checks.

**Comment by Emantor** [comment]
As long as pdudaemon upstream can't properly work with labgrid, I am in favor of merging this driver.
Please go ahaead. You might also want to look into supporting the remote infrastructure.

**Comment by Emantor** [comment]
Hi @niecore, its been a while, do you intend to finish this PR?

**Comment by niecore** [comment]
@Emantor I found out that the current implementation is not suitable for the remote infrastructure. 

I am still int the progress of making and testing the adaption.
Since the implementation will be very different from what is shown in the current PR, it would also be possible to close this PR.

**Comment by Emantor** [comment]
> @Emantor I found out that the current implementation is not suitable for the remote infrastructure.
> 
> I am still int the progress of making and testing the adaption.
> Since the implementation will be very different from what is shown in the current PR, it would also be possible to close this PR.

Thanks, doing so now. Feel free to open a draft PR at any time :+1:

**Comment by JPEWdev** [comment]
FWIW, I have a PR to add support for this to pdudaemon: https://github.com/pdudaemon/pdudaemon/pull/92

**Pull request closed without merging**
