### PR TITLE
driver/shelldriver: handle devices that do not have a login prompt

### PR DESCRIPTION
**Pull request by ejoerns**
For example when using a minimal initramfs system, we might not even
have a login prompt to catch. With the current implementation the only
way of handling this is to set 'login_prompt' to a string that will
never be machted which is quite inconvenient.

A better handling is to make the 'login_prompt' optional, respectively
allow passing `login_prompt=""`.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 
- [ ] The arguments and description in doc/configuration.rst have been updated
- [ ] Add a section on how to use the feature to doc/usage.rst
- [ ] CHANGES.rst has been updated
- [x] PR has been tested

Please provide a comment if this is the way to go or if we care for API breakage here (because of moved attribute).

### CODE REVIEW

**Comment by basti2342** [comment]
While looking at this I noticed the default values for the ShellDriver's attributes are a little vague, at least `password` . There are cases where a password is requested and an empty password is regarded okay. This is currently not possible. I'd suggest to use `attr.ib(default=None, validator=attr.validators.optional(attr.validators.instance_of(str)`. This allows a string or `None`.

Looking at the introduced default `login_prompt` defaulting to an empty string and check for emptiness before feeding it into expect is might be okay. But IMO it's cleaner to default to `None` as suggested for `password`.

**Comment by ejoerns** [comment]
I agree that there are boards that either have a) a password, b) no password, c) an empty password.
And that the 3rd case seems to be broken because of https://github.com/labgrid-project/labgrid/blob/master/labgrid/driver/shelldriver.py#L142

Thus, yes we should default to `None` there and allow setting empty string explicitly.
I don't expect it to make a difference for the login prompt, but I would not argue against keeping defaults consistent.

**Comment by Emantor** [comment]
Okay, please rebase your PR and switch to None. I'll create an issue for the password entry.

**Comment by Emantor** [comment]
Closing this, shelldriver has been refactored since.

**Pull request closed without merging**
