### PR TITLE
driver/power: add support for Gude Expert Power Control 8225

### PR DESCRIPTION
**Pull request by userid0x0**
**Description**
This patch adds support for Gude Expert Power Control 8225 using the HTTP-GET API defined at wiki.gude.info/EPC_HTTP_Interface .

Signed-off-by: Alexander Merkle <alexander.merkle@lauterbach.com>

**Checklist**
- [x] Documentation for the feature
- [ ] Tests for the feature 

- [x] The arguments and description in doc/configuration.rst have been updated

- [x] PR has been tested

### CODE REVIEW

**Review by Bastian-Krause — APPROVED** [review]
Looks good. Thanks!

**Review by jluebbe — APPROVED** [review]

**Comment by Bastian-Krause** [comment]
@userid0x0 Please note that we want to get rid of power backends supported by pdudaemon in the long run: #1031

**Comment by userid0x0** [comment]
Thanks for the notice. Let me take a look to PDUDaemon as well.

**Comment by Emantor** [comment]
Thanks for the PR. Yeah, there are some issues with PDUDaemon currently, especially in regards to power readout support.

**Pull request merged**
