### PR TITLE
ExternalPowerDriver: split into Port and Driver

### PR DESCRIPTION
**Pull request by leiflm**
To support the export of an ExternalPowerDriver as a resource,
split the declaration into Driver and Port.

Signed-off-by: Leif Middelschulte <leif.middelschulte@klsmartin.com>

**Description**
Allow `ExternalPowerDriver` to be exported as a resource, like `PDUDaemonPort`.

**Checklist**
- [x] Documentation for the feature
- [x] Tests for the feature 

- [x] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [x] CHANGES.rst has been updated

- [x] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Comment by leiflm** [comment]
I'm not sure whether this should be a resource or rather be implemented using the `Agent` mechanism.

**Comment by jluebbe** [comment]
The ExternalPowerDriver was mainly intended as a quick alternative for local setups, not for use with exporters. The resource doesn't really correspond to an interface.
I'd very much prefer if we could use the PDUDaemon support for that (see https://github.com/pdudaemon/pdudaemon/pull/78). There shouldn't too much work left to get that merged, but I've been unable to find some spare cycles for that. @mattface seems busy as well. :)

**Comment by jluebbe** [comment]
This would break existing users of the ExternalPowerDriver, right?

**Comment by leiflm** [comment]
> This would break existing users of the ExternalPowerDriver, right?

Yes, it would. I [mentioned](https://github.com/labgrid-project/labgrid/pull/635/files#diff-db23dcd814354c954091a9b90dbfd92aR63) it in the *Breaking changes in 0.3.0*-section accordingly.

**Comment by Emantor** [comment]
What kind of resource am I locking in this case? I'd much rather add proper support via a power driver than making the ExternalPowerDriver remote capable.

**Comment by leiflm** [comment]
> What kind of resource am I locking in this case? 

You'd lock a power supply that is linked to a place. But this is not really about locking, but about the process of announcement, acquiring and using a *Place*.

> I'd much rather add proper support via a power driver

[Done](https://github.com/pdudaemon/pdudaemon/pull/85), a while ago.

> than making the ExternalPowerDriver remote capable.

Fair enough. This was just about declaring obscure/ad-hoc setups (devices and their resources) via a single `labgrid-exporter`.

So if you feel uncomfortable with this change, close it.

**Pull request closed without merging**
