### PR TITLE
Use --hostname to override export host name

### PR DESCRIPTION
**Pull request by kjeldflarup**
When exporting USBSerialPort the exporter exports the host as the hostname. This may however not always resolve. 

setting LG_HOSTNAME to ex an IP address will override gethostname() in the exporter
This variable can be used with ex. USBSerialPort, USBGenericExport, USBSigrokExport
Tested with USBSerialPort only.

### CODE REVIEW

**Comment by jluebbe** [comment]
There is already the --name parameter to set the name used to register resources. I've added a commit on top which implements an --hostname parameter instead of an environment variable. So far I've only tested it without real hardware.

**Comment by kjeldflarup** [comment]
Could I get a copy of Your commit?

**Comment by jluebbe** [comment]
@kjeldflarup It's in this PR branch. See https://github.com/labgrid-project/labgrid/pull/218/commits/144e3b810bc70e528d152eca036f7f45b2b22d06

**Comment by kjeldflarup** [comment]
I have testet this on my Raspberry Pi and found it working.

**Pull request merged**
