### PR TITLE
remote: client: bootstrap: pass args to load function

### PR DESCRIPTION
**Pull request by bitshifter1**
**Description**
We would like to be able to pass multiple arguments to our bootstrap driver. This allows us to configure it without having to modify the config, e.g. bootstrapping different kind of images that require different logic.

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [x] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Comment by Emantor** [comment]
I assume your bootstrap driver is out of tree? Can you find an in-tree usage for this PR?

**Comment by bitshifter1** [comment]
> I assume your bootstrap driver is out of tree? Can you find an in-tree usage for this PR?

Hi @Emantor , sorry for my late responds. Yes we have an off-tree driver. I am not exactly sure what you mean by in-tree usage :sweat_smile: The OpenOCDDriver already makes use of the generic **args arguments, but it does it by passing them through the constructor. It would be nice that also the of-tree bootstrapdrivers can make use of the self.args.bootstrap_args arguments passed to the client. Our client call looks like this.

`labgrid-client bootstrap barebox.img type=barebox device=flash`

**Comment by bitshifter1** [comment]
> I assume your bootstrap driver is out of tree? Can you find an in-tree usage for this PR?

Hi @Emantor , sorry for my late responds. Yes we have an off-tree driver. I am not exactly sure what you mean by in-tree usage :sweat_smile: The OpenOCDDriver already makes use of the generic **args arguments, but it does it by passing them through the constructor. It would be nice that also the of-tree bootstrapdrivers can make use of the self.args.bootstrap_args arguments passed to the client. Our client call looks like this.

`labgrid-client bootstrap barebox.img type=barebox device=flash`

**Comment by Emantor** [comment]
My real intention was to nudge you to submit your own bootstrapdriver to upstream, improving labgrid support and your own driver through the review :grin:

**Comment by bitshifter1** [comment]
> My real intention was to nudge you to submit your own bootstrapdriver to upstream, improving labgrid support and your own driver through the review grin

Our bootstrap driver is very specific and wouldn't serve much purpose for anyone else 😊

**Comment by jluebbe** [comment]
Merging this would mean that we can never add more keyword arguments to the `load()` function without potentially breaking a use-case we don't know about. Also, passing `filename=foo` would overwrite the normal filename argument which is at least confusing.

The benefit of passing them via the constructor (like with OpenOCDDriver) is that you have an interface specific to that driver in the environment yaml. The labgrid-client commands are more generic.

@bitshifter1 Your example looks like you're writing an image to flash? Please note that the Bootstrap protocol is intended for loading and executing a bootloader in RAM, not for writing it to some storage.

**Comment by bitshifter1** [comment]
> The benefit of passing them via the constructor (like with OpenOCDDriver) is that you have an interface specific to that driver in the environment yaml. The labgrid-client commands are more generic.

@jluebbe yes makes sense, no problem. Thanks anyway!!!

**Pull request closed without merging**
