### PR TITLE
client: fix help parser of labgrid-client tmc

### PR DESCRIPTION
**Pull request by userid0x0**
**Description**
The command
```
  labgrid-client tmc
```
showed the help of last subparser (=export). Now it shows the help of TMC including all subcommands.

Signed-off-by: Alexander Merkle <alexander.merkle@lauterbach.com>

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [x] PR has been tested

### CODE REVIEW

**Comment by jluebbe** [comment]
Do you have an explanation of why using a copy of the subparser fixes this?

**Comment by userid0x0** [comment]
The lambda gets evaluated with the `args.func(session)` call https://github.com/labgrid-project/labgrid/blob/76101cd02d8d4585abb31a28878945b6dd6f361b/labgrid/remote/client.py#L1956 . At this point the `subparser` variable holds a reference to the export subparser created here https://github.com/labgrid-project/labgrid/blob/76101cd02d8d4585abb31a28878945b6dd6f361b/labgrid/remote/client.py#L1885 . So it's a problem when the lamda gets evaluated.

Thus I am taking a deep-copy of the TMC subparser once it's fully created.

**Comment by userid0x0** [comment]
Update: I just see that the deep-copy is a bit of an overkill. Saving a reference of the `subparser` should be enough as well.
```
- tmc_parser = copy.deepcopy(subparser)
+ tmc_parser = subparser
```

**Comment by jluebbe** [comment]
Perhaps we should just use different names for every subparser used in lambdas?

**Comment by Bastian-Krause** [comment]
CI seems broken. Could you wrap your commit message at 74 chars per line and force-push your branch, so CI runs again? Thanks!

**Review by Bastian-Krause — APPROVED** [review]
Thanks!

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
