### PR TITLE
driver/commandmixin: Add poll_until_success helper function

### PR DESCRIPTION
**Pull request by nefethael**
Signed-off-by: Vincent Prince <vincent.prince.fr@gmail.com>

### CODE REVIEW

**Comment by nefethael** [comment]
I removed try catch as it was useless.

**Comment by Emantor** [comment]
The documentation strings have been updated by me, please review again so we can get this merged.

**Comment by Emantor** [comment]
@jluebbe please take a look at this again, should be ready to go.

**Comment by jluebbe** [comment]
I've fixed the return values and rebased the changes.

**Comment by Emantor** [comment]
I rebased again and resolved the conflicts, I'll wait for a CI run and than merge.

**Pull request merged**
