### PR TITLE
driver/sshdriver: Allow filename to be a folder

### PR DESCRIPTION
**Pull request by mrabule1**
Adding a "-r" in front of filename helps with folders, and it still works
with regular files.
Prior to commit 1d7b97b838f7, something like this was working:
ssh.put('-r <folder_name>', '<remote_location>')
but afterwards, scp fails with "unknown option --".
Add a similar change for ssh.put

Fixes: 1d7b97b838f7 (driver/sshdriver: Allow whitespaces in filenames Prevent filenames with whitespaces from beeing split.)

Signed-off-by: Mirela Rabulea <mirela.rabulea@nxp.com>

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [ ] PR has been tested

- [ ] Man pages have been regenerated

### CODE REVIEW

**Comment by Emantor** [comment]
Please add a test for directory transfer in `tests/test_sshdriver.py`.

**Comment by mrabule1** [comment]
Hi,
it would save me some time if I had the "right" instructions to run tests/test_sshdriver.py
After running exactly the labgrid installation steps from here:
https://labgrid.readthedocs.io/en/latest/development.html#installation
I tried to run:
python -m pytest --verbose tests/test_sshdriver.py 
It seems the test_local_put/get are skipped:

======================================================== test session starts ========================================================
platform linux -- Python 3.6.9, pytest-5.3.1, py-1.9.0, pluggy-0.13.1 -- /work/mirela/labgrid/venv/bin/python
cachedir: .pytest_cache
rootdir: /work/mirela/labgrid, inifile: setup.cfg
plugins: cov-2.8.1, isort-0.3.1, mock-1.12.1, pylint-0.14.1, dependency-0.4.0
collected 8 items                                                                                                                   

tests/test_sshdriver.py::test_create_fail_missing_resource PASSED                                                             [ 12%]
tests/test_sshdriver.py::test_create PASSED                                                                                   [ 25%]
tests/test_sshdriver.py::test_run_check PASSED                                                                                [ 37%]
tests/test_sshdriver.py::test_run_check_raise PASSED                                                                          [ 50%]
tests/test_sshdriver.py::test_local_put SKIPPED                                                                               [ 62%]
tests/test_sshdriver.py::test_local_get SKIPPED                                                                               [ 75%]
tests/test_sshdriver.py::test_local_run SKIPPED                                                                               [ 87%]
tests/test_sshdriver.py::test_local_run_check SKIPPED                                                                         [100%]

=================================================== 4 passed, 4 skipped in 0.14s ====================================================

Thanks.

**Comment by Emantor** [comment]
Yes, for the local SSHDriver tests you'll need to add `--local-sshmanager --ssh-username <username>` after `python -m pytest`  where `<username>` needs to be a user which is able to connect without a password to localhost.

**Comment by mrabule1** [comment]
Hi,
thanks for the info.
I added the requested tests.
This passes, nothing skipped:
python -m pytest --local-sshmanager --ssh-username mrabule1 --verbose tests/test_sshdriver.py

One observation, it seems the user which may connect without a password to localhost, has to be the same as the current user, and which is running in venv.

This, for example does not work, even if labgrid is also a user which may connect without a password to localhost:
ssh labgrid@localhost  => works without password
(venv) mrabule1@mrabule1-MacBookPro:/work/mirela/labgrid$ python -m pytest --local-sshmanager --ssh-username labgrid --verbose tests/test_sshdriver.py
ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --local-sshmanager --ssh-username tests/test_sshdriver.py
  inifile: /work/mirela/labgrid/setup.cfg
  rootdir: /work/mirela/labgrid

(venv) mrabule1@mrabule1-MacBookPro:/work/mirela/labgrid$

**Comment by Emantor** [comment]
The travis failure is related to incompatibilities in python 3.5, but your changes look fine.
In your error message it looks like pytest isn't parsing the local cli options correctly, maybe it has to do with the `python -m pytest` invocation instead of calling `pytest` directly.

I'll retest your changes locally, thanks!

**Review by Emantor — APPROVED** [review]

**Pull request merged**
