### PR TITLE
driver/shelldriver: Retry login to shell

### PR DESCRIPTION
**Pull request by jremmet**
Some boards have issues on login. They get wrong user names the first
time. For this case also send a empty password to get login into a sane
state. After that just retry and leave a info message.

Signed-off-by: Jan Remmet <j.remmet@phytec.de>

### CODE REVIEW

**Comment by jremmet** [comment]
For me this work around #27.
Maybe we need a configuration switch?

**Comment by jluebbe** [comment]
I'd like to avoid workarounds in the low-level drivers for special cases like this. Instead I tried to solve similar problems on one of our boards with this work-in-progess change: [jluebbe/labgrid wip/txdealy](/jluebbe/labgrid/tree/wip/txdelay).
Does that help for your problem as well?
Also, if you problem is related to logging in, you may be affected by #27.

**Comment by jremmet** [comment]
Yes it looks like #27. 
With 'txdelay: 0.001' your changes works reliable. (tested with ttyUSB0) With the 0.05 from the example I was afraid that the sum of wait from all bytes may to big.

**Comment by jluebbe** [comment]
While it would nice to only use txdelay for the login, that should be done in a separate pull request.

**Pull request closed without merging**
