### PR TITLE
managed file: adds api to fetch a file

### PR DESCRIPTION
**Pull request by nvincent-vossloh**
**description**
Use `ManagedFile` to be able to pull file from resource, it is useful when a binary on the resource creates a file which needs to be accessible on the client side.
I tested this feature in my environment which uses labgrid.

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 
- [ ] The arguments and description in doc/configuration.rst have been updated
- [ ] Add a section on how to use the feature to doc/usage.rst
- [ ] Add a section on how to use the feature to doc/development.rst
- [ ] PR has been tested

I could need help regarding adding a test for this feature and which documentations files needs to be updated.

Thanks.

### CODE REVIEW

**Comment by Emantor** [comment]
Hi,

all drivers which created files on the exporter side so far took care of either opening a channel back to the client, i.e. via SSH and pipes or sync the requested data back automatically. I don't see why we need a generic mechanism which allows syncing files back to the client, the driver should already take care of that. This also extends the `ManagedFile` scope to be bidirectional.

**Comment by nvincent-vossloh** [comment]
> Hi,
> 
> all drivers which created files on the exporter side so far took care of either opening a channel back to the client, i.e. via SSH and pipes or sync the requested data back automatically. I don't see why we need a generic mechanism which allows syncing files back to the client, the driver should already take care of that. This also extends the `ManagedFile` scope to be bidirectional.

Hi,

Thanks for your reply, I may have misunderstood something.
My use case is a [custom driver](https://github.com/SiemaApplications/labgrid/blob/dda69a2515d18396816a97f63ebcc63bcae8afe4/labgrid/driver/stlinkdriver.py#L60) to manage st-link probe, I wish to dump the firmware on the MCU connected to the probe, therefore the file is created on the remote host by the probe and I want to get the dumped firmware to the client, in that sense it is more a fetch rather than a sync since the file was never on the client in the first place.

**Comment by Bastian-Krause** [comment]
You could open the new file locally and make `STM32_Programmer_CLI` write to stdout and pass the file handle as `stdout=` in `subprocess.Popen()`. No need for any additional file transfer, no tmpfiles. See `start_record()` in #1157 as an example.

**Comment by nvincent-vossloh** [comment]
> You could open the new file locally and make `STM32_Programmer_CLI` write to stdout and pass the file handle as `stdout=` in `subprocess.Popen()`. No need for any additional file transfer, no tmpfiles. See `start_record()` in #1157 as an example.

Thank you for the tip, I will look into it and update this issue.

**Comment by Emantor** [comment]
If you have additional questions or require feedback, either open a new PR or [join the chat](https://app.element.io/#/room/#labgrid:matrix.org).

**Pull request closed without merging**
