### PR TITLE
CHANGES: update CHANGES.rst for 23.0

### PR DESCRIPTION
**Pull request by Emantor**
**Description**
Changelog update to prepare for the release.

### CODE REVIEW

**Comment by jluebbe** [comment]
We should mention that with https://github.com/labgrid-project/labgrid/pull/959, the AndroidFastboot matches need to be adjusted (`…/RemoteAndroidUSBFastboot` instead of `…/NetworkAndroidFastboot`.

**Comment by Bastian-Krause** [comment]
Since we use `YY.MINOR[.MICRO]` versioning, could you update the calver badge in the README to `https://img.shields.io/badge/calver-YY.MINOR%5B.MICRO%5D-22bfda.svg`?

**Comment by Bastian-Krause** [comment]
Maybe we should communicate our deprecation intentions more clearly as described in https://github.com/labgrid-project/labgrid/pull/1081#issuecomment-1404873491?

Quoting from that comment:
> We should also announce this plan in the release notes of the [next release](https://github.com/labgrid-project/labgrid/milestone/8).

**Comment by Emantor** [comment]
> We should mention that with #959, the AndroidFastboot matches need to be adjusted (`…/RemoteAndroidUSBFastboot` instead of `…/NetworkAndroidFastboot`.

This was already mentioned in the new features section. I have added an additional line in breaking changes.

**Comment by Emantor** [comment]
> Maybe we should communicate our deprecation intentions more clearly as described in [#1081 (comment)](https://github.com/labgrid-project/labgrid/pull/1081#issuecomment-1404873491)?
> 
> Quoting from that comment:
> 
> > We should also announce this plan in the release notes of the [next release](https://github.com/labgrid-project/labgrid/milestone/8).

This is mentioned in the breaking changes section.

**Review by Bastian-Krause — APPROVED** [review]
Added more features and bug fixes to CHANGES.rst, fixed some typos.

**Pull request merged**
