### PR TITLE
Bump Requirements to Latest Releases

### PR DESCRIPTION
**Pull request by Bastian-Krause**
**Description**
- bump requirements to recent versions (vmprof tip of master)
- update system dependencies
- fix pytest deprecation warnings caused by the new pytest version
- set crossbar's "user_timeout" in default config

**Known Issues**
- vmprof not pinned to a release, see: https://github.com/vmprof/vmprof-python/issues/240

**Checklist**
- [ ] CHANGES.rst has been updated
- [x] PR has been tested

### CODE REVIEW

**Review by krevsbech — DISMISSED** [review]
Looks good to me

**Comment by Bastian-Krause** [comment]
@krevsbech I hoped you could shed some light on the docker issue mentioned above. I couldn't reproduce this locally if I remember correctly.

**Comment by Bastian-Krause** [comment]
- rebased
- version bump autobahn/crossbar 22.1.1 -> 22.2.2
- fixed another occurrence of "PytestRemovedIn8Warning: Passing None has been deprecated." in `tests/test_environment.py`

**Comment by Bastian-Krause** [comment]
> **Known Issues**
> 
> * vmprof not pinned to a release, see: [Please release new version to pypi (python 3.10 issue) vmprof/vmprof-python#240](https://github.com/vmprof/vmprof-python/issues/240

See also: https://github.com/crossbario/crossbar/issues/2002

**Comment by Bastian-Krause** [comment]
- dropped commit "remote: coordinator: use dump(), load() from util.yaml" which was implemented and merged with #931
- rebased on master

**Comment by Bastian-Krause** [comment]
The next crossbar release should have vmprof as a soft dependency: https://github.com/crossbario/crossbar/pull/2035

I'll update the requirements once it is released, then we should be good to go to merge this PR.

**Comment by Bastian-Krause** [comment]
Superseded by #1001.

**Pull request closed without merging**
